# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1517149976);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1517150096);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1517225480);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1517149856);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1517151374);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1517149736);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1516873918);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1517150216);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 58);
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1516905000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1517153335);
user_pref("browser.onboarding.notification.prompt-count", 4);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1517154228294");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1517156028294");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1517152446630");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1517156046630");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20171116103757");
user_pref("browser.startup.homepage_override.buildID", "20171116103757");
user_pref("browser.startup.homepage_override.mstone", "57.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":12,\"newElementCount\":2}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20180125);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.ipc.processCount.web", 4);
user_pref("e10s.rollout.cohort", "multiBucket4");
user_pref("e10s.rollout.cohortSample", "0.470045");
user_pref("e10s.rollout.cohortSample.multi", "0.873694");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 23);
user_pref("extensions.e10s.rollout.blocklist", "");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.e10sMultiBlockedByAddons", false);
user_pref("extensions.getAddons.cache.lastUpdate", 1516873440);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20171116103757");
user_pref("extensions.lastAppVersion", "57.0");
user_pref("extensions.lastPlatformVersion", "57.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.startupExperimentPrefs.browser.urlbar.matchBuckets", "suggestion:4,general:5");
user_pref("extensions.shield-recipe-client.user_id", "c403d316-3603-4dd3-a0b4-2eb810de1274");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{528de3d9-4b0f-40d2-a08a-e9ec23c779bb}\",\"addons\":{\"disable-media-wmf-nv12@mozilla.org\":{\"version\":\"1.1\"},\"disable-crash-autosubmit@mozilla.org\":{\"version\":\"2.1\"},\"disable-js-shared-memory@mozilla.org\":{\"version\":\"2.0\"}}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"861ed2b6-b7db-4994-a993-a6a3bba56c1d\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1517149970);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1516873347);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20171116103757");
user_pref("media.gmp-manager.lastCheck", 1517149651);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1516873896);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1517149409);
user_pref("services.blocklist.clock_skew_seconds", 692);
user_pref("services.blocklist.gfx.checked", 1517149409);
user_pref("services.blocklist.last_update_seconds", 1517149409);
user_pref("services.blocklist.onecrl.checked", 1517149409);
user_pref("services.blocklist.plugins.checked", 1517149409);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1516873896);
user_pref("toolkit.startup.last_success", 1517225446);
user_pref("toolkit.telemetry.cachedClientID", "a07aad3d-71ed-415b-9b44-0714b2e3962f");
user_pref("toolkit.telemetry.previousBuildID", "20171116103757");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
